import { StyleSheet, I18nManager } from 'react-native';
import type { AppColors } from '@dawwar/theme';
import { space, typography, radius } from '@dawwar/theme';

export const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    userCard: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: space.base,
      paddingVertical: space.lg,
      backgroundColor: colors.background,
      gap: space.sm,
    },
    loginCard: {
      marginHorizontal: space.base,
      marginBottom: space.lg,
      padding: space.base,
      borderRadius: radius.lg,
      backgroundColor: colors.primary,
    },
    loginButton: {
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.surface,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: space.sm,
    },
    loginButtonText: {
      ...typography.body1,
      color: colors.primary,
      fontWeight: '800',
    },
    userName: {
      ...typography.body1,
      color: colors.primary,
      fontWeight: '800',
      textAlign: 'auto',
    },
    userPhone: {
      ...typography.caption,
      color: colors.textSecondary,
      textAlign: 'auto',
    },
    userTextCol: {
      flex: 1,
      gap: 3,
      alignItems: 'flex-start',
    },
    userMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    avatarContainer: {
      position: 'relative',
    },
    editIconContainer: {
      position: 'absolute',
      bottom: 0,
      end: 0,
      backgroundColor: colors.primary,
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
    },
    profileEditBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sectionLabel: {
      ...typography.caption,
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      paddingHorizontal: space.base,
      paddingTop: space.base,
      paddingBottom: space.sm,
      flex:1,
      alignSelf:"flex-start",
    },
    walletBalanceCard: {
      marginHorizontal: space.base,
      marginBottom: space.base,
      minHeight: 74,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.card,
      paddingHorizontal: space.base,
      flexDirection: 'row',
      alignItems: 'center',
      gap: space.md,
    },
    walletIconBubble: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    walletTextCol: {
      flex: 1,
      gap: 2,
    },
    walletTitle: {
      ...typography.body2,
      color: colors.textSecondary,
      fontWeight: '700',
      textAlign: 'auto',
    },
    walletAmount: {
      ...typography.h4,
      color: colors.text,
      fontWeight: '900',
      textAlign: 'auto',
    },
    sectionCard: {
      backgroundColor: colors.background,
      marginHorizontal: space.sm,
      marginBottom: space.base,
      overflow: 'hidden',
    },
    preferences: {
      backgroundColor: colors.background,
      marginHorizontal: space.sm,
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
      paddingTop: space.sm,
    },
    logoutPill: {
      height: 50,
      marginHorizontal: space.base,
      marginBottom: space.lg,
      borderRadius: 25,
      backgroundColor: colors.primaryLight,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: space.sm,
    },
    logoutPillText: {
      ...typography.body2,
      color: colors.primary,
      fontWeight: '800',
    },
    languageChip: {
      minWidth: 76,
      paddingHorizontal: space.sm,
      paddingVertical: 5,
      borderRadius: radius.sm,
      borderWidth: 1,
      borderColor: colors.border,
      color: colors.text,
      textAlign: 'center',
    },
    versionText: {
      ...typography.caption,
      color: colors.textDisabled,
      textAlign: 'center',
      padding: space.xl,
    },
    logoutRow: { 
      backgroundColor: colors.card, 
      marginTop: space.md,
      marginBottom: space.sm,
      borderWidth: 1,
      borderColor: `${colors.error}20`,
    },
  });
