import { StyleSheet } from 'react-native';
import type { AppColors } from '@dawwar/theme';
import { space, typography, radius, shadows } from '@dawwar/theme';

export const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    timelineContainer: {
      backgroundColor: colors.card,
      paddingHorizontal: space.base,
      paddingVertical: space.lg,
      marginBottom: space.sm,
    },
    statusLabel: {
      ...typography.h4,
      color: colors.text,
      textAlign: 'center',
      marginTop: space.base,
    },
    driverCard: {
      backgroundColor: '#FFE2A3',
      marginHorizontal: space.base,
      borderRadius: radius.full,
      padding: space.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: space.md,
      marginBottom: space.sm,
      ...shadows.md,
    },
    driverInfo: { flex: 1 },
    driverName: { ...typography.label, color: colors.text },
    driverMeta: { ...typography.caption, color: colors.textSecondary },
    driverActions: {
      flexDirection: 'row',
      gap: space.xs,
    },
    callBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(255,255,255,0.45)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cancelBtn: {
      margin: space.base,
    },
    mapPanel: {
      height: 350,
      marginHorizontal: space.base,
      marginBottom: space.sm,
      borderRadius: radius.lg,
      overflow: 'hidden',
      backgroundColor: colors.surfaceVariant,
      position: 'relative',
    },
    mapGrid: {
      ...StyleSheet.absoluteFillObject,
      opacity: 0.7,
    },
    mapRoad: {
      position: 'absolute',
      width: '130%',
      height: 18,
      backgroundColor: '#fff',
    },
    routeBase: {
      position: 'absolute',
      left: '33%',
      top: '22%',
      width: 7,
      height: '58%',
      borderRadius: 4,
      backgroundColor: colors.textDisabled,
      transform: [{ rotate: '36deg' }],
    },
    routeActive: {
      position: 'absolute',
      left: '45%',
      bottom: '24%',
      width: 7,
      borderRadius: 4,
      backgroundColor: colors.primary,
      transform: [{ rotate: '36deg' }],
    },
    storePin: {
      position: 'absolute',
      left: '24%',
      bottom: '24%',
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: colors.primary,
    },
    driverPin: {
      position: 'absolute',
      right: '30%',
      top: '16%',
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: colors.primary,
    },
    locateBtn: {
      position: 'absolute',
      right: 12,
      top: 12,
      width: 38,
      height: 38,
      borderRadius: 10,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      ...shadows.sm,
    },
    infoRow: {
      marginHorizontal: space.base,
      paddingVertical: space.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    infoLabel: {
      ...typography.body2,
      color: colors.text,
      fontWeight: '800',
    },
    infoValue: {
      ...typography.body2,
      color: colors.textSecondary,
    },
    detailsLink: {
      ...typography.caption,
      color: colors.primary,
      fontWeight: '800',
    },
  });
