import { StyleSheet } from 'react-native';
import type { AppColors } from '@dawwar/theme';
import { radius, space, typography } from '@dawwar/theme';

export const createStyles = (colors: AppColors, _isRTL: boolean) =>
  StyleSheet.create({
    content: {
      flexGrow: 1,
      paddingHorizontal: space.xl,
      paddingTop: space.sm,
      paddingBottom: space['4xl'],
      backgroundColor: colors.background,
      gap: space.lg,
    },
    header: {
      minHeight: 76,
      paddingHorizontal: space.xl,
      paddingTop: space.md,
      paddingBottom: space.sm,
      backgroundColor: colors.background,
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerAction: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.shadow,
      shadowOpacity: 1,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    headerActionGhost: {
      opacity: 0,
    },
    headerTitleWrap: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      ...typography.h4,
      color: colors.text,
      fontWeight: '800',
      textAlign: 'center',
    },
    promoCodeRow: {
      minHeight: 54,
      borderRadius: radius.md,
      backgroundColor: colors.surfaceVariant,
      borderWidth: 1,
      borderColor: colors.borderLight,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: space.base,
      gap: space.sm,
    },
    promoCodeInput: {
      ...typography.body1,
      flex: 1,
      minHeight: 52,
      color: colors.text,
      textAlign: 'auto',
    },
    promoCodeApply: {
      ...typography.buttonSm,
      color: colors.primary,
      fontWeight: '800',
    },
    sectionTitle: {
      ...typography.body2,
      color: colors.textSecondary,
      textAlign: 'auto',
      marginTop: space.sm,
    },
    rowsGroup: {
      gap: space.md,
    },
    emptyText: {
      ...typography.body2,
      color: colors.textTertiary,
      textAlign: 'auto',
      paddingVertical: space.md,
    },
    promoRow: {
      minHeight: 54,
      borderRadius: radius.md,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: space.base,
      gap: space.md,
    },
    promoRowDisabled: {
      opacity: 0.36,
    },
    promoTitle: {
      ...typography.body1,
      flex: 1,
      color: colors.text,
      fontWeight: '800',
      textAlign: 'auto',
    },
    promoInfoButton: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.textDisabled,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkBox: {
      width: 22,
      height: 22,
      borderRadius: radius.sm,
      borderWidth: 2,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
    },
    checkBoxSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    getMoreButton: {
      minHeight: 54,
      borderRadius: radius.md,
      backgroundColor: colors.primaryLight,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: space.sm,
      marginTop: space.sm,
    },
    getMoreText: {
      ...typography.button,
      color: colors.primary,
      fontWeight: '800',
    },
    footer: {
      paddingHorizontal: space.xl,
      paddingTop: space.md,
      paddingBottom: space.xl,
      backgroundColor: colors.background,
    },
    sheetContent: {
      alignItems: 'center',
      gap: space.lg,
      paddingHorizontal: space.xl,
      paddingBottom: space['2xl'],
    },
    sheetIconWrap: {
      width: 86,
      height: 86,
      borderRadius: 30,
      backgroundColor: colors.warningBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sheetTitle: {
      ...typography.h4,
      color: colors.text,
      fontWeight: '900',
      textAlign: 'center',
    },
    sheetDetails: {
      alignSelf: 'stretch',
      gap: space.md,
    },
    detailLabel: {
      ...typography.body2,
      color: colors.text,
      fontWeight: '900',
      textAlign: 'auto',
    },
    detailValue: {
      ...typography.body2,
      color: colors.textSecondary,
      textAlign: 'auto',
    },
  });
