import { StyleSheet } from 'react-native';
import type { AppColors } from '@dawwar/theme';
import { radius, space, typography } from '@dawwar/theme';

export const createStyles = (colors: AppColors, _isRTL: boolean) =>
  StyleSheet.create({
    content: {
      flexGrow: 1,
      paddingHorizontal: space.xl,
      paddingTop: space.base,
      paddingBottom: space['4xl'],
      backgroundColor: colors.background,
    },
    header: {
      minHeight: 76,
      paddingHorizontal: space.xl,
      paddingTop: space.md,
      paddingBottom: space.sm,
      backgroundColor: colors.background,
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerAction: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.shadow,
      shadowOpacity: 1,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    headerActionGhost: {
      opacity: 0,
    },
    headerTitleWrap: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      ...typography.h4,
      color: colors.text,
      fontWeight: '800',
      textAlign: 'center',
    },
    form: {
      flex: 1,
      gap: space.lg,
    },
    avatarSection: {
      alignItems: 'center',
      paddingTop: space.lg,
      paddingBottom: space.sm,
    },
    avatarButton: {
      width: 152,
      height: 152,
      borderRadius: 76,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarImage: {
      width: 152,
      height: 152,
      borderRadius: 76,
      backgroundColor: colors.surfaceVariant,
    },
    avatarPlaceholder: {
      width: 152,
      height: 152,
      borderRadius: 76,
      backgroundColor: colors.surfaceVariant,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarHead: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: colors.border,
      marginBottom: space.sm,
    },
    avatarBody: {
      width: 84,
      height: 40,
      borderTopLeftRadius: 44,
      borderTopRightRadius: 44,
      backgroundColor: colors.border,
    },
    avatarEdit: {
      position: 'absolute',
      top: 4,
      end: 0,
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: colors.background,
    },
    field: {
      minHeight: 54,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceVariant,
      paddingHorizontal: space.base,
      flexDirection: 'row',
      alignItems: 'center',
      gap: space.sm,
    },
    fieldError: {
      borderColor: colors.error,
    },
    fieldInput: {
      ...typography.body1,
      flex: 1,
      minHeight: 52,
      paddingVertical: 0,
      color: colors.text,
      textAlign: 'auto',
      writingDirection: _isRTL ? 'rtl' : 'ltr',
    },
    fieldText: {
      ...typography.body1,
      flex: 1,
      color: colors.text,
      textAlign: 'auto',
      writingDirection: _isRTL ? 'rtl' : 'ltr',
    },
    fieldPlaceholder: {
      color: colors.placeholder,
    },
    fieldAccessory: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space.sm,
    },
    countryFlag: {
      fontSize: 24,
      lineHeight: 28,
    },
    countryCode: {
      ...typography.body2,
      color: colors.textSecondary,
      writingDirection: 'ltr',
    },
    errorText: {
      ...typography.caption,
      color: colors.error,
      marginTop: -space.md,
      textAlign: 'auto',
    },
    footer: {
      paddingHorizontal: space.xl,
      paddingTop: space.md,
      paddingBottom: space.xl,
      backgroundColor: colors.background,
      gap: space.md,
    },
    skipText: {
      ...typography.body1,
      color: colors.textTertiary,
      textAlign: 'center',
    },
    datePickerBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.48)',
      justifyContent: 'flex-end',
    },
    datePickerSheet: {
      borderTopStartRadius: radius.xl,
      borderTopEndRadius: radius.xl,
      backgroundColor: colors.background,
      paddingHorizontal: space.xl,
      paddingTop: space.xl,
      paddingBottom: space.xl,
      gap: space.lg,
    },
    datePickerTitle: {
      ...typography.h4,
      color: colors.text,
      fontWeight: '800',
      textAlign: 'center',
    },
    datePickerColumns: {
      height: 220,
      flexDirection: 'row',
      gap: space.md,
    },
    datePickerColumn: {
      flex: 1,
      borderRadius: radius.lg,
      backgroundColor: colors.surfaceVariant,
    },
    datePickerOption: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.md,
      margin: 4,
    },
    datePickerOptionText: {
      ...typography.body1,
      color: colors.text,
      fontWeight: '700',
      textAlign: 'center',
    },
    datePickerActions: {
      flexDirection: 'row',
      gap: space.md,
    },
    datePickerAction: {
      flex: 1,
      minHeight: 48,
      borderRadius: radius.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceVariant,
    },
    datePickerConfirmAction: {
      backgroundColor: colors.primary,
    },
    datePickerCancelText: {
      ...typography.label,
      color: colors.text,
      fontWeight: '800',
      textAlign: 'center',
    },
    datePickerConfirmText: {
      ...typography.label,
      color: colors.primaryText,
      fontWeight: '800',
      textAlign: 'center',
    },
  });
